name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync files to server
      run: |
        rsync -avz --exclude='.github' --exclude='.git' ./wordpress/ vy@192.168.1.16:C:\wamp64\www\chuyende\wordpress 
      env:
        RSYNC_RSH: 'ssh -o StrictHostKeyChecking=no'

    - name: Restart Apache
      run: |
        ssh vy@192.168.1.16:C:\wamp64\www\chuyende\wordpress 'sudo systemctl restart apache2'